### ISSUE TITLE
Addon not working in Blender 5.0

### ISSUE THREAD

**Issue by Whizziy** [naelstrof/blender-jiggle-physics#25]
This happen when i try to bake the jiggle

Python: Traceback (most recent call last):
  File "C:\Users\[Redacted]\AppData\Roaming\Blender Foundation\Blender\5.0\extensions\blender_org\jiggle_physics\__init__.py", line 1136, in poll
    return context.scene.jiggle.enable and context.object and not context.object.jiggle.mute and context.active_pose_bone and context.active_pose_bone.jiggle.enable and not is_bone_animated(context.active_pose_bone.id_data, context.active_pose_bone.name)
                                                                                                                                                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\[Redacted]\AppData\Roaming\Blender Foundation\Blender\5.0\extensions\blender_org\jiggle_physics\__init__.py", line 463, in is_bone_animated
    for fcurve in anim_data.action.fcurves:
                  ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Action' object has no attribute 'fcurves'
